### ISSUE TITLE
RemoteForward Issues

### ISSUE THREAD

**Issue by joshuarubin** [MisterTea/EternalTerminal#228]
A few issues related to `RemoteForward`:

1. I have a `RemoteForward` option in my `~/.ssh/config` that causes a port conflict when I also use `et -rt`. Can you cause et to always disable the `RemoteForward` option when calling ssh? It doesn't seem like it should _ever_ be correct for it to be enabled in ssh when using et.
2. It would also be amazing to, in addition to the above comment, automatically parse the `RemoteForward` option that ssh would have used and apply it as an `et -rt` option.
3. The `et` server crashes if I connect with `RemoteForward` enabled (I'm using `et -x -rt="2489:2489" <host>`). Then `exit` and then reconnect with the same command. I have to restart the `et` server to connect again. Connecting again (after first using `RemoteForward`) without `-rt` works fine)

**Comment by MisterTea** [comment]
I believe #3 is fixed in ET 6.0.  #1 (add -o RemoteForward=no to the ssh command) and #2 (parse RemoteForward option in ssh_config) should be easy for you to add  and we can merge your changes into master :-).

**Comment by joshuarubin** [comment]
I've got `master` installed on both the server and client but #3 isn't fixed:
```
Sep 09 19:33:48 balerion systemd[1]: et.service: Main process exited, code=killed, status=6/ABRT
Sep 09 19:33:48 balerion systemd[1]: et.service: Failed with result 'signal'.
```

**Comment by MisterTea** [comment]
In 6.0, -rt was changed to just -r.

**Comment by joshuarubin** [comment]
Yeah. Figured that out. The server is still dying.

**Comment by MisterTea** [comment]
Can you get a stack trace from the logs or by running the server under gdb?

**Comment by joshuarubin** [comment]
[etserver-2019-09-12_01-08.log](https://github.com/MisterTea/EternalTerminal/files/3604138/etserver-2019-09-12_01-08.log)
